from django.urls import path,include
from . import views

urlpatterns = [
    path("",views.home, name="home"),
    path("accounts/",include("django.contrib.auth.urls")),
    path("register/",views.register, name="register"),
    path("dashboard/",views.dashboard, name="dashboard"),
    path("profile/",views.profile, name="profile"),
    path("update_profile/",views.update_profile, name="update_profile"),
    path("project_create/",views.project_create, name="project_create"),
    path("project_edit/<int:pk>",views.project_edit, name="project_edit"),
    path("project_delete/<int:pk>",views.project_delete, name="project_delete"),
    path("project_details/<int:pk>",views.project_details, name="project_details"),
    path("add_inventory/<int:pk>",views.add_inventory, name="add_inventory"),
    path("add_inventory_more/<int:pk>",views.add_inventory_more, name="add_inventory_more"),
    path("add_inventory_details/<int:pk>",views.add_inventory_details, name="add_inventory_details"),
    path("add_inventory_delete/<int:pk>/<int:inv>",views.add_inventory_delete, name="add_inventory_delete"),
    path("used_inventory/<int:pk>",views.used_inventory, name="used_inventory"),
    path("used_inventory_more/<int:pk>",views.used_inventory_more, name="used_inventory_more"),
    path("used_inventory_detail/<int:pk>",views.used_inventory_detail, name="used_inventory_detail"),
    path("used_inventory_delete/<int:pk>/<int:inv>",views.used_inventory_delete, name="used_inventory_delete"),
    path("in_stock_inventory/<int:pk>",views.in_stock_inventory, name="in_stock_inventory"),
    path("in_stock_inventory_more/<int:pk>",views.in_stock_inventory_more, name="in_stock_inventory_more"),
    path("in_stock_inventory_details/<int:pk>",views.in_stock_inventory_details, name="in_stock_inventory_details"),
    path("in_stock_inventory_delete/<int:pk>/<int:inv>",views.in_stock_inventory_delete, name="in_stock_inventory_delete"),
    path("daily_workers/<int:pk>",views.daily_workers, name="daily_workers"),
    path("daily_workers_list/<int:pk>",views.daily_workers_list, name="daily_workers_list"),
    path("daily_workers_detail/<int:pk>",views.daily_workers_detail, name="daily_workers_detail"),
    path("daily_workers_delete/<int:pk>/<int:inv>",views.daily_workers_delete, name="daily_workers_delete"),
    path("inspection/<int:pk>",views.inspection, name="inspection"),
    path("inspection_list/<int:pk>",views.inspection_list, name="inspection_list"),
    path("inspection_detail/<int:pk>",views.inspection_detail, name="inspection_detail"),
    path("inspection_details_delete/<int:pk>/<int:inv>",views.inspection_details_delete, name="inspection_details_delete"),
    path("material_shifting/",views.material_shifting, name="material_shifting"),
    path("material_shifting_list/",views.material_shifting_list, name="material_shifting_list"),
    path("material_shifting_detail/<int:pk>",views.material_shifting_detail, name="material_shifting_detail"),
    path("material_shifting_delete/<int:pk>",views.material_shifting_delete, name="material_shifting_delete"),
    path("punch_in/<int:pk>",views.punch_in, name="punch_in"),
    path("lunch_start/<int:pk>",views.lunch_start, name="lunch_start"),
    path("lunch_end/<int:pk>",views.lunch_end, name="lunch_end"),
    path("punch_out/<int:pk>",views.punch_out, name="punch_out"),
    path("project_plan/",views.project_plan, name="project_plan"),
    path("project_plan_list/",views.project_plan_list, name="project_plan_list"),
    path("project_plan_details/<int:pk>",views.project_plan_details, name="project_plan_details"),
  
]