# Generated by Django 5.2 on 2025-04-18 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_attendance_project_alter_inventory_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lunch_start_lat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_start_lon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_end_lat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_end_lon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_in_lat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_in_lon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_lat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_lon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, choices=[('M-sand', 'M-sand'), ('P-sand', 'P-sand')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('Engineer', 'Engineer'), ('Department Engineer', 'Department Engineer'), ('Supervisor', 'Supervisor'), ('Site Supervisor', 'Site Supervisor'), ('Site Worker Writer', 'Site Worker Writer'), ('Mestri', 'Mestri'), ('Worker', 'Worker')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Inventory_use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('M-sand', 'M-sand'), ('P-sand', 'P-sand')], default='', max_length=255)),
                ('qty', models.CharField(blank=True, default='', max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='inventory/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lon', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material_shifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.CharField(blank=True, choices=[('JCB', 'JCB'), ('Canter', 'Canter'), ('Tata-ace', 'Tata-ace'), ('Lorre', 'Lorre'), ('Tractor', 'Tractor'), ('Tipper', 'Tipper'), ('Auto', 'Auto')], default='', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('Material_name', models.ImageField(blank=True, choices=[('P-sand', 'P-sand'), ('M-sand', 'M-sand'), ('Derbies', 'Derbies')], default='', max_length=25, upload_to='')),
                ('lon', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_project', to='base.project')),
                ('to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_project', to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='profile/')),
                ('aadhar', models.CharField(blank=True, default='', max_length=55)),
                ('pan', models.CharField(blank=True, default='', max_length=55)),
                ('bank_account', models.CharField(blank=True, default='', max_length=55)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=55)),
                ('role', models.CharField(blank=True, choices=[('Gareea', 'Gareea')], max_length=35, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_daily_work_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('no_of_workers', models.CharField(blank=True, default='', max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('project_work_status', models.ImageField(blank=True, default='', max_length=25, upload_to='')),
                ('lon', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_work_inspection_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('no_of_workers', models.CharField(blank=True, default='', max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('project_work_status', models.ImageField(blank=True, default='', max_length=25, upload_to='')),
                ('lon', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stocks_in_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('M-sand', 'M-sand'), ('P-sand', 'P-sand')], default='', max_length=255)),
                ('qty', models.CharField(blank=True, default='', max_length=25)),
                ('price', models.CharField(blank=True, default='', max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='inventory/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lon', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Project_workers',
        ),
    ]
