# Generated by Django 5.2 on 2025-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_attendance_lunch_start_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, choices=[('M-sand', 'M-sand'), ('P-sand', 'P-sand'), ('Gehelli', 'Gehelli')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory_use',
            name='name',
            field=models.CharField(blank=True, choices=[('M-sand', 'M-sand'), ('P-sand', 'P-sand'), ('Gehelli', 'Gehelli')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('Auto', 'Auto'), ('JCB', 'JCB'), ('Canter', 'Canter'), ('Tractor', 'Tractor'), ('Lorre', 'Lorre'), ('Tipper', 'Tipper'), ('Tata-ace', 'Tata-ace')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stocks_in_inventory',
            name='name',
            field=models.CharField(blank=True, choices=[('M-sand', 'M-sand'), ('P-sand', 'P-sand'), ('Gehelli', 'Gehelli')], default='', max_length=255),
        ),
    ]
