# Generated by Django 5.2 on 2025-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_inventory_name_alter_inventory_use_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='Material_name',
            field=models.ImageField(blank=True, choices=[('Derbies', 'Derbies'), ('P-sand', 'P-sand'), ('M-sand', 'M-sand')], default='', max_length=25, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('JCB', 'JCB'), ('Lorre', 'Lorre'), ('Tipper', 'Tipper'), ('Canter', 'Canter'), ('Tata-ace', 'Tata-ace'), ('Auto', 'Auto'), ('Tractor', 'Tractor')], default='', max_length=255),
        ),
    ]
