# Generated by Django 5.2 on 2025-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_material_shifting_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_shifting',
            name='Material_name',
            field=models.ImageField(blank=True, choices=[('P-sand', 'P-sand'), ('Derbies', 'Derbies'), ('M-sand', 'M-sand')], default='', max_length=25, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('JCB', 'JCB'), ('Tata-ace', 'Tata-ace'), ('Tipper', 'Tipper'), ('Canter', 'Canter'), ('Auto', 'Auto'), ('Tractor', 'Tractor'), ('Lorre', 'Lorre')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project_work_inspection_details',
            name='project_work_status',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
