# Generated by Django 5.2 on 2025-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_material_shifting_material_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='punch_end_lat',
            new_name='lunch_end_lat',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='punch_end_lon',
            new_name='lunch_end_lon',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_bank_name',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_branch_name',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='', max_length=155),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Odisha', 'Odisha'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('Mizoram', 'Mizoram'), ('Chandigarh', 'Chandigarh'), ('TamilNadu', 'TamilNadu'), ('Delhi', 'Delhi'), ('Nagaland', 'Nagaland'), ('Meghalaya', 'Meghalaya'), ('Ladakh', 'Ladakh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Puducherry', 'Puducherry'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Jharkhand', 'Jharkhand'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Telangana', 'Telangana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Maharashtra', 'Maharashtra'), ('Lakshadweep', 'Lakshadweep'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Punjab', 'Punjab'), ('Bihar', 'Bihar'), ('West Bengal', 'West Bengal'), ('Chhattisgarh', 'Chhattisgarh'), ('Haryana', 'Haryana'), ('Uttarakhand', 'Uttarakhand'), ('Karnataka', 'Karnataka'), ('Manipur', 'Manipur'), ('Tripura', 'Tripura')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, choices=[('M Sand', 'M Sand'), ('P Sand', 'P Sand'), ('Cement', 'Cement'), ('Stone - 20mm', 'Stone - 20mm'), ('Stone - 40mm', 'Stone - 40mm'), ('Stone - 60mm', 'Stone - 60mm'), ('RMC', 'RMC'), ('Steel', 'Steel'), ('Granite', 'Granite'), ('Aluminum Window', 'Aluminum Window'), ('ACP', 'ACP'), ('Sanitary Item', 'Sanitary Item'), ('Electric Item', 'Electric Item'), ('Bricks', 'Bricks'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('PVC Pipes', 'PVC Pipes'), ('GI Pipes', 'GI Pipes'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('School desk and furniture', 'School desk and furniture'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('UPS and Batteries', 'UPS and Batteries'), ('LED Street light', 'LED Street light'), ('Street light High Mast Poles', 'Street light High Mast Poles'), ('Stones', 'Stones')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory_use',
            name='name',
            field=models.CharField(blank=True, choices=[('M Sand', 'M Sand'), ('P Sand', 'P Sand'), ('Cement', 'Cement'), ('Stone - 20mm', 'Stone - 20mm'), ('Stone - 40mm', 'Stone - 40mm'), ('Stone - 60mm', 'Stone - 60mm'), ('RMC', 'RMC'), ('Steel', 'Steel'), ('Granite', 'Granite'), ('Aluminum Window', 'Aluminum Window'), ('ACP', 'ACP'), ('Sanitary Item', 'Sanitary Item'), ('Electric Item', 'Electric Item'), ('Bricks', 'Bricks'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('PVC Pipes', 'PVC Pipes'), ('GI Pipes', 'GI Pipes'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('School desk and furniture', 'School desk and furniture'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('UPS and Batteries', 'UPS and Batteries'), ('LED Street light', 'LED Street light'), ('Street light High Mast Poles', 'Street light High Mast Poles'), ('Stones', 'Stones')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='Material_name',
            field=models.CharField(blank=True, choices=[('Aluminum Window', 'Aluminum Window'), ('P Sand', 'P Sand'), ('Steel', 'Steel'), ('School desk and furniture', 'School desk and furniture'), ('ACP', 'ACP'), ('PVC Pipes', 'PVC Pipes'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Bricks', 'Bricks'), ('Street light High Mast Poles', 'Street light High Mast Poles'), ('Stone - 20mm', 'Stone - 20mm'), ('Granite', 'Granite'), ('Debris', 'Debris'), ('Sanitary Item', 'Sanitary Item'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('RMC', 'RMC'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('Cement', 'Cement'), ('Electric Item', 'Electric Item'), ('Stone - 40mm', 'Stone - 40mm'), ('Stone - 60mm', 'Stone - 60mm'), ('M Sand', 'M Sand'), ('LED Street light', 'LED Street light'), ('UPS and Batteries', 'UPS and Batteries'), ('GI Pipes', 'GI Pipes'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('Stones', 'Stones')], default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('JCB', 'JCB'), ('Auto', 'Auto'), ('Tata-ace', 'Tata-ace'), ('Tipper', 'Tipper'), ('Tractor', 'Tractor'), ('Lorre', 'Lorre'), ('Canter', 'Canter')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Gare Workers', 'Gare Workers'), ('Male Helper', 'Male Helper'), ('Female Helper', 'Female Helper'), ('Paint Workers', 'Paint Workers'), ('Electrical Workers', 'Electrical Workers'), ('Plumbing Workers', 'Plumbing Workers'), ('Granite Workers', 'Granite Workers'), ('Tile Workers', 'Tile Workers'), ('Welding Workers', 'Welding Workers'), ('Aluminum Window Workers', 'Aluminum Window Workers'), ('ACC Workers', 'ACC Workers'), ('Stone Cladding Workers', 'Stone Cladding Workers'), ('Batch Workers', 'Batch Workers'), ('Structural Workers', 'Structural Workers'), ('Borewell Workers', 'Borewell Workers'), ('Street Light Workers', 'Street Light Workers'), ('UPS Workers', 'UPS Workers'), ('CC Camera Workers', 'CC Camera Workers'), ('LED Name Board Workers', 'LED Name Board Workers')], max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='stocks_in_inventory',
            name='name',
            field=models.CharField(blank=True, choices=[('M Sand', 'M Sand'), ('P Sand', 'P Sand'), ('Cement', 'Cement'), ('Stone - 20mm', 'Stone - 20mm'), ('Stone - 40mm', 'Stone - 40mm'), ('Stone - 60mm', 'Stone - 60mm'), ('RMC', 'RMC'), ('Steel', 'Steel'), ('Granite', 'Granite'), ('Aluminum Window', 'Aluminum Window'), ('ACP', 'ACP'), ('Sanitary Item', 'Sanitary Item'), ('Electric Item', 'Electric Item'), ('Bricks', 'Bricks'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('PVC Pipes', 'PVC Pipes'), ('GI Pipes', 'GI Pipes'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('School desk and furniture', 'School desk and furniture'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('UPS and Batteries', 'UPS and Batteries'), ('LED Street light', 'LED Street light'), ('Street light High Mast Poles', 'Street light High Mast Poles'), ('Stones', 'Stones')], default='', max_length=255),
        ),
    ]
