# Generated by Django 5.2 on 2025-04-24 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_attendance_lunch_in_photo_attendance_lunch_out_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_shifting',
            name='Material_name',
            field=models.CharField(blank=True, choices=[('Stone - 20mm', 'Stone - 20mm'), ('Granite', 'Granite'), ('PVC Pipes', 'PVC Pipes'), ('GI Pipes', 'GI Pipes'), ('Aluminum Window', 'Aluminum Window'), ('School desk and furniture', 'School desk and furniture'), ('UPS and Batteries', 'UPS and Batteries'), ('Electric Item', 'Electric Item'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('LED Street light', 'LED Street light'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('Cement', 'Cement'), ('Debris', 'Debris'), ('Steel', 'Steel'), ('RMC', 'RMC'), ('Bricks', 'Bricks'), ('Sanitary Item', 'Sanitary Item'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Stone - 60mm', 'Stone - 60mm'), ('Stones', 'Stones'), ('P Sand', 'P Sand'), ('ACP', 'ACP'), ('M Sand', 'M Sand'), ('Stone - 40mm', 'Stone - 40mm'), ('Street light High Mast Poles', 'Street light High Mast Poles')], default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('JCB', 'JCB'), ('Lorre', 'Lorre'), ('Tipper', 'Tipper'), ('Tractor', 'Tractor'), ('Tata-ace', 'Tata-ace'), ('Auto', 'Auto'), ('Canter', 'Canter')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('TamilNadu', 'TamilNadu'), ('Kerala', 'Kerala'), ('Bihar', 'Bihar'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Odisha', 'Odisha'), ('Himachal Pradesh', 'Himachal Pradesh'), ('West Bengal', 'West Bengal'), ('Goa', 'Goa'), ('Jharkhand', 'Jharkhand'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra'), ('Uttarakhand', 'Uttarakhand'), ('Nagaland', 'Nagaland'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Sikkim', 'Sikkim'), ('Mizoram', 'Mizoram'), ('Ladakh', 'Ladakh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Gujarat', 'Gujarat'), ('Meghalaya', 'Meghalaya'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Manipur', 'Manipur'), ('Lakshadweep', 'Lakshadweep'), ('Karnataka', 'Karnataka'), ('Tripura', 'Tripura'), ('Puducherry', 'Puducherry'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu')], default='', max_length=155),
        ),
        migrations.CreateModel(
            name='project_pre_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project_plan_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_pre_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project_pre_plan')),
            ],
        ),
    ]
