# Generated by Django 5.2 on 2025-05-09 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_material_shifting_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='project_lunch_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_end', to='base.project'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='project_lunch_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_start', to='base.project'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='project_punch_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punch_out', to='base.project'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image1',
            field=models.ImageField(blank=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image2',
            field=models.ImageField(blank=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image3',
            field=models.ImageField(blank=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='invoice_image1',
            field=models.ImageField(blank=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='invoice_image2',
            field=models.ImageField(blank=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='invoice_image3',
            field=models.ImageField(blank=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='material_taken_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='material_taken_phone',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shop_image',
            field=models.ImageField(blank=True, upload_to='inventory/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhar_image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
        migrations.AddField(
            model_name='profile',
            name='others',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_attendance', to='base.project'),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='Material_name',
            field=models.CharField(blank=True, choices=[('Stone - 40mm', 'Stone - 40mm'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('Debris', 'Debris'), ('School desk and furniture', 'School desk and furniture'), ('PVC Pipes', 'PVC Pipes'), ('Steel', 'Steel'), ('Stones', 'Stones'), ('Granite', 'Granite'), ('Aluminum Window', 'Aluminum Window'), ('Stone - 20mm', 'Stone - 20mm'), ('GI Pipes', 'GI Pipes'), ('Cement', 'Cement'), ('ACP', 'ACP'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Electric Item', 'Electric Item'), ('Bricks', 'Bricks'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('P Sand', 'P Sand'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('Street light High Mast Poles', 'Street light High Mast Poles'), ('Sanitary Item', 'Sanitary Item'), ('LED Street light', 'LED Street light'), ('UPS and Batteries', 'UPS and Batteries'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('RMC', 'RMC'), ('Stone - 60mm', 'Stone - 60mm'), ('M Sand', 'M Sand')], default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('Tata-ace', 'Tata-ace'), ('Tipper', 'Tipper'), ('Lorre', 'Lorre'), ('Canter', 'Canter'), ('Auto', 'Auto'), ('JCB', 'JCB'), ('Tractor', 'Tractor')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Gare Workers', 'Gare Workers'), ('Male Helper', 'Male Helper'), ('Female Helper', 'Female Helper'), ('Paint Workers', 'Paint Workers'), ('Electrical Workers', 'Electrical Workers'), ('Plumbing Workers', 'Plumbing Workers'), ('Granite Workers', 'Granite Workers'), ('Tile Workers', 'Tile Workers'), ('Welding Workers', 'Welding Workers'), ('Aluminum Window Workers', 'Aluminum Window Workers'), ('ACC Workers', 'ACC Workers'), ('Stone Cladding Workers', 'Stone Cladding Workers'), ('Batch Workers', 'Batch Workers'), ('Structural Workers', 'Structural Workers'), ('Borewell Workers', 'Borewell Workers'), ('Street Light Workers', 'Street Light Workers'), ('UPS Workers', 'UPS Workers'), ('CC Camera Workers', 'CC Camera Workers'), ('LED Name Board Workers', 'LED Name Board Workers'), ('Retail Shop', 'Retail Shop'), ('wholesale Shop', 'wholesale Shop'), ('Distributor', 'Distributor'), ('Factory', 'Factory')], max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Ladakh', 'Ladakh'), ('Punjab', 'Punjab'), ('Lakshadweep', 'Lakshadweep'), ('Nagaland', 'Nagaland'), ('TamilNadu', 'TamilNadu'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Kerala', 'Kerala'), ('Puducherry', 'Puducherry'), ('Telangana', 'Telangana'), ('Chhattisgarh', 'Chhattisgarh'), ('Haryana', 'Haryana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jharkhand', 'Jharkhand'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Sikkim', 'Sikkim'), ('Mizoram', 'Mizoram'), ('West Bengal', 'West Bengal'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Maharashtra', 'Maharashtra'), ('Meghalaya', 'Meghalaya'), ('Rajasthan', 'Rajasthan'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Odisha', 'Odisha'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chandigarh', 'Chandigarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Manipur', 'Manipur'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Gujarat', 'Gujarat'), ('Karnataka', 'Karnataka')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('Engineer', 'Engineer'), ('Department Engineer', 'Department Engineer'), ('Supervisor', 'Supervisor'), ('Site Supervisor', 'Site Supervisor'), ('Site Worker Writer', 'Site Worker Writer'), ('Mestri', 'Mestri'), ('Worker', 'Worker'), ('Supplier', 'Supplier'), ('Founder', 'Founder'), ('Owner', 'Owner'), ('Chairman', 'Chairman'), ('CEO', 'CEO'), ('Partner', 'Partner'), ('Investor', 'Investor'), ('Shop Owner', 'Shop Owner')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Material_shifting_received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('Material_name', models.CharField(blank=True, choices=[('Stone - 40mm', 'Stone - 40mm'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('Debris', 'Debris'), ('School desk and furniture', 'School desk and furniture'), ('PVC Pipes', 'PVC Pipes'), ('Steel', 'Steel'), ('Stones', 'Stones'), ('Granite', 'Granite'), ('Aluminum Window', 'Aluminum Window'), ('Stone - 20mm', 'Stone - 20mm'), ('GI Pipes', 'GI Pipes'), ('Cement', 'Cement'), ('ACP', 'ACP'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Electric Item', 'Electric Item'), ('Bricks', 'Bricks'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('P Sand', 'P Sand'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('Street light High Mast Poles', 'Street light High Mast Poles'), ('Sanitary Item', 'Sanitary Item'), ('LED Street light', 'LED Street light'), ('UPS and Batteries', 'UPS and Batteries'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('RMC', 'RMC'), ('Stone - 60mm', 'Stone - 60mm'), ('M Sand', 'M Sand')], default='', max_length=225)),
                ('lon', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
