# Generated by Django 5.2 on 2025-05-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_attendance_project_lunch_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='Material_name',
            field=models.CharField(blank=True, choices=[('Street light High Mast Poles', 'Street light High Mast Poles'), ('Sanitary Item', 'Sanitary Item'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('UPS and Batteries', 'UPS and Batteries'), ('Bricks', 'Bricks'), ('ACP', 'ACP'), ('RMC', 'RMC'), ('Stones', 'Stones'), ('Stone - 60mm', 'Stone - 60mm'), ('Aluminum Window', 'Aluminum Window'), ('Granite', 'Granite'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('Debris', 'Debris'), ('M Sand', 'M Sand'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Stone - 40mm', 'Stone - 40mm'), ('PVC Pipes', 'PVC Pipes'), ('P Sand', 'P Sand'), ('LED Street light', 'LED Street light'), ('GI Pipes', 'GI Pipes'), ('Electric Item', 'Electric Item'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('Cement', 'Cement'), ('Stone - 20mm', 'Stone - 20mm'), ('Steel', 'Steel'), ('School desk and furniture', 'School desk and furniture')], default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('JCB', 'JCB'), ('Auto', 'Auto'), ('Lorre', 'Lorre'), ('Canter', 'Canter'), ('Tractor', 'Tractor'), ('Tipper', 'Tipper'), ('Tata-ace', 'Tata-ace')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material_shifting_received',
            name='Material_name',
            field=models.CharField(blank=True, choices=[('Street light High Mast Poles', 'Street light High Mast Poles'), ('Sanitary Item', 'Sanitary Item'), ('Borewell Pumpset Materials', 'Borewell Pumpset Materials'), ('Concrete Solid Blocks 8', 'Concrete Solid Blocks 8'), ('UPS and Batteries', 'UPS and Batteries'), ('Bricks', 'Bricks'), ('ACP', 'ACP'), ('RMC', 'RMC'), ('Stones', 'Stones'), ('Stone - 60mm', 'Stone - 60mm'), ('Aluminum Window', 'Aluminum Window'), ('Granite', 'Granite'), ('Green Board and Notice Board', 'Green Board and Notice Board'), ('Debris', 'Debris'), ('M Sand', 'M Sand'), ('Concrete Solid Blocks 6', 'Concrete Solid Blocks 6'), ('Stone - 40mm', 'Stone - 40mm'), ('PVC Pipes', 'PVC Pipes'), ('P Sand', 'P Sand'), ('LED Street light', 'LED Street light'), ('GI Pipes', 'GI Pipes'), ('Electric Item', 'Electric Item'), ('Concrete Solid Blocks 4', 'Concrete Solid Blocks 4'), ('Cement', 'Cement'), ('Stone - 20mm', 'Stone - 20mm'), ('Steel', 'Steel'), ('School desk and furniture', 'School desk and furniture')], default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Goa', 'Goa'), ('Meghalaya', 'Meghalaya'), ('Bihar', 'Bihar'), ('Puducherry', 'Puducherry'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Haryana', 'Haryana'), ('Karnataka', 'Karnataka'), ('Ladakh', 'Ladakh'), ('West Bengal', 'West Bengal'), ('Sikkim', 'Sikkim'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Manipur', 'Manipur'), ('Jharkhand', 'Jharkhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Lakshadweep', 'Lakshadweep'), ('TamilNadu', 'TamilNadu'), ('Delhi', 'Delhi'), ('Chhattisgarh', 'Chhattisgarh'), ('Tripura', 'Tripura'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra'), ('Uttarakhand', 'Uttarakhand'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Punjab', 'Punjab'), ('Nagaland', 'Nagaland'), ('Rajasthan', 'Rajasthan'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Mizoram', 'Mizoram'), ('Gujarat', 'Gujarat'), ('Kerala', 'Kerala'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Odisha', 'Odisha')], default='', max_length=155),
        ),
    ]
