# Generated by Django 5.2 on 2025-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_profile_shop_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory_use',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='Material_name',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='vehicle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material_shifting_received',
            name='Material_name',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Manipur', 'Manipur'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Rajasthan', 'Rajasthan'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Goa', 'Goa'), ('TamilNadu', 'TamilNadu'), ('Jharkhand', 'Jharkhand'), ('Meghalaya', 'Meghalaya'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Puducherry', 'Puducherry'), ('Chandigarh', 'Chandigarh'), ('Tripura', 'Tripura'), ('Gujarat', 'Gujarat'), ('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Ladakh', 'Ladakh'), ('Bihar', 'Bihar'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Nagaland', 'Nagaland'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Kerala', 'Kerala'), ('Sikkim', 'Sikkim'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Chhattisgarh', 'Chhattisgarh'), ('Uttarakhand', 'Uttarakhand'), ('Odisha', 'Odisha'), ('Lakshadweep', 'Lakshadweep'), ('Telangana', 'Telangana'), ('Mizoram', 'Mizoram')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='stocks_in_inventory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
